name: 'aws-cicd'

on:
  push:
    branches:
    - ahmedak01-dev/test1
  pull_request:

jobs:
  dev-deploy:
    name: 'aws-dev-cicd'
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

 # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=cloud/AWS/dev init
    
    # Terraform Format
    - name: Terraform Format
      run: terraform -chdir=cloud/AWS/dev fmt

     # Terraform Validate
    - name: Terraform Validate
      run: terraform -chdir=cloud/AWS/dev validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=cloud/AWS/dev plan

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    # - name: Terraform Apply
    #   run: terraform -chdir=cloud/AWS/dev apply -auto-approve

    # - name: Terraform Destroy
    #   run: terraform -chdir=cloud/AWS/dev destroy -auto-approve


  stage-deploy:
    name: 'aws-stage-cicd'
    runs-on: ubuntu-latest
    environment: staging
    needs: dev-deploy

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

 # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=cloud/AWS/stage init
    
    # Terraform Format
    - name: Terraform Format
      run: terraform -chdir=cloud/AWS/stage fmt

     # Terraform Validate
    - name: Terraform Validate
      run: terraform -chdir=cloud/AWS/stage validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=cloud/AWS/stage plan

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    # - name: Terraform Apply
    #   run: terraform -chdir=cloud/AWS/stage apply -auto-approve

    # - name: Terraform Destroy
    #   run: terraform -chdir=cloud/AWS/stage destroy -auto-approve


  prod-deploy:
    name: 'aws-prod-cicd'
    runs-on: ubuntu-latest
    environment: production
    needs: stage-deploy

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=cloud/AWS/prod init
    
    # Terraform Format
    - name: Terraform Format
      run: terraform -chdir=cloud/AWS/prod fmt

     # Terraform Validate
    - name: Terraform Validate
      run: terraform -chdir=cloud/AWS/prod validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=cloud/AWS/prod plan

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    # - name: Terraform Apply
    #   run: terraform -chdir=cloud/AWS/prod apply -auto-approve

    # - name: Terraform Destroy
    #   run: terraform -chdir=cloud/AWS/prod destroy -auto-approve

